### ISSUE TITLE
Missing timelines / Deadlines

### ISSUE THREAD

**Issue by Qclaire** [mikeattara/GADS2020-Roadmap#11]
It's good to lay out everything that needs to be covered. But could you also attach the specific timelines and deadlines at which expect learners to have covered certain materials? For instance, there is no indication of when phase 1 begins or ends and nothing on phase 2. That makes it hard to plan around the program or effectively distribute the course load over the span of time allocated. I hope you resolve this soon

**Comment by Nyamador** [comment]
Thanks for the heads up @Qclaire , we'd take a look at that and add the necessary timelines like you suggested.

**Comment by CHISOM96** [comment]
Hello guys I think an update should come after phase 2 content has been made available

**Comment by Nyamador** [comment]
That's okay. I'll close the issue for now.
